{{ $_ := set . "Values" (fromYaml (include "common.tplvalues.render" ( dict "value" .Values "context" $ ))) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doltlab.fullname" . }}-webui
  labels:
    app: webui
{{ include "doltlab.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.webUi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "doltlab.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: webui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "doltlab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: webui
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "doltlab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.webUi }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webUi.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          {{- range $pkey, $pval := .Values.webUi.env }}
          - name: {{ $pkey }}
            value: {{ $pval }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
