{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "doltlab.serviceAccountName" . }}
  labels:
{{ include "doltlab.labels" . | indent 4 }}
{{- end }}
